"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { ProjectContractNotice } from "@/components/projects/project-contract-notice";
import { ProjectStatusBadge } from "@/components/projects/project-status-badge";

const sections = ["Contract value", "Total budget", "Total expenses", "Remaining budget", "Completed work", "Remaining work"];
export default function ProjectDetailsPage() { const { id } = useParams<{ id: string }>(); return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-orange-600">Project detail</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Project {id}</h1><div className="mt-3 flex items-center gap-3"><ProjectStatusBadge status="UNKNOWN" /><span className="text-sm text-slate-500">Progress unavailable</span></div></div><Link href={`/projects/${id}/edit`} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Edit project</Link></div><div className="mt-7"><ProjectContractNotice /></div><section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sections.map((title) => <article key={title} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-slate-600">{title}</p><p className="mt-3 text-2xl font-bold text-slate-400">Unavailable</p><p className="mt-1 text-xs text-slate-500">Project API required</p></article>)}</section><section className="mt-7 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Project information</h2><p className="mt-3 text-sm leading-6 text-slate-500">Client, location, road measurements, contract, supervisor, dates, and status will load from the project response DTO.</p></div><div className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Timeline and activity</h2><p className="mt-3 text-sm leading-6 text-slate-500">Timeline, photos, documents, and activities require project activity and file APIs.</p></div></section></div>; }
