// Mirrors AttendanceDTO. Every timestamp is generated by the backend; the client only formats it.

export type AttendanceState = 'NOT_CHECKED_IN' | 'CHECKED_IN' | 'CHECKED_OUT';

// Mirrors AttendanceDTO.EventResponse: the outcome of a check-in or check-out.
// The check-out fields are absent for a check-in.
export interface AttendanceEvent {
  workerId: string;
  employeeId?: string;
  workerName?: string;
  attendanceDate: string;
  checkInTime: string;
  checkOutTime?: string;
  checkInMethod: string;
  checkOutMethod?: string;
  workDuration?: string;
  status: Exclude<AttendanceState, 'NOT_CHECKED_IN'>;
}

// Mirrors AttendanceDTO.Session: one work session inside a day.
export interface AttendanceSession {
  id: string;
  projectId: string;
  checkInTime: string;
  checkOutTime?: string;
  checkInMethod?: string;
  checkOutMethod?: string;
  durationSeconds?: number;
}

// Mirrors AttendanceDTO.DailySummary. First check-in and last check-out span the whole day;
// totalWorkSeconds is the sum of the closed sessions.
export interface DailyAttendance {
  workerId: string;
  employeeId?: string;
  workerName?: string;
  attendanceDate: string;
  firstCheckInTime?: string;
  lastCheckOutTime?: string;
  totalWorkSeconds: number;
  totalWorkDuration: string;
  status: AttendanceState;
  sessions: AttendanceSession[];
}
