"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ErrorState, Loading } from "@/components/common/states";
import { useAuth } from "@/hooks/useAuth";
import { healthApi, type HealthStatus } from "@/lib/api/health-api";
import { useWorkspace } from "@/components/workspace/workspace-context";
import { BrandLogo } from "@/components/branding/brand-logo";
import { PublicLandingPage } from "@/components/landing/public-landing-page";

const actionByRole: Record<string, Array<[string, string]>> = {
  ADMIN: [["New project", "/projects"], ["Add expense", "/expenses"], ["Review approvals", "/approval-inbox"], ["Build report", "/report-builder"]],
  CONTRACTOR: [["New project", "/projects"], ["Add expense", "/expenses"], ["Review approvals", "/approval-inbox"], ["Build report", "/report-builder"]],
  SUPERVISOR: [["Mark attendance", "/attendance"], ["Daily progress", "/daily-progress"], ["Site diary", "/site-diary"], ["Report issue", "/issues"]],
  WORKER: [["My attendance", "/attendance"], ["My work queue", "/work-queue"], ["My payments", "/payments"], ["Current shift", "/shifts"]],
};
const attentionItems = ["Project health", "Budget control", "Payment radar", "Approvals", "Document expiry"];
function getGreeting(hour: number) { return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; }
function PendingCard({ title, detail }: { title: string; detail: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold text-slate-900">{title}</h3><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-amber-800">API required</span></div><p className="mt-5 text-2xl font-bold text-slate-400">Unavailable</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>; }
function SectionTitle({ title, link }: { title: string; link?: [string, string] }) { return <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold tracking-tight text-slate-900">{title}</h2>{link && <Link href={link[1]} className="text-sm font-semibold text-orange-600 hover:text-orange-700">{link[0]}</Link>}</div>; }

export default function HomePage() {
  const { user, loading: authLoading } = useAuth();
  const { projectId } = useWorkspace();
  const [health, setHealth] = useState<HealthStatus | null>(null);
  const [healthError, setHealthError] = useState("");
  const [now, setNow] = useState<Date | null>(null);
  useEffect(() => { setNow(new Date()); void healthApi.getStatus().then((status) => setHealth(status)).catch((reason: { message?: string }) => setHealthError(reason.message || "Backend is unavailable.")); }, []);
  if (authLoading) return <main className="grid min-h-screen place-items-center"><Loading /></main>;
  if (!user) return <PublicLandingPage />;
  const role = user?.role || "CONTRACTOR";
  const actions = actionByRole[role] || actionByRole.CONTRACTOR;
  const date = now?.toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }) || "Preparing today's command center...";
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,_#fff4df,_transparent_38%),var(--background)] px-4 py-6 text-slate-900 sm:px-6 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-wrap items-center justify-between gap-4"><BrandLogo /><nav className="flex items-center gap-3 text-sm"><Link href="/notifications" className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-semibold">Notifications</Link>{user ? <Link href="/profile" className="rounded-lg bg-slate-900 px-3 py-2 font-semibold text-white">{user.firstName}</Link> : <Link href="/login" className="rounded-lg bg-slate-900 px-3 py-2 font-semibold text-white">Sign in</Link>}</nav></header>
    <section className="mt-10 flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-600">Contractor command center</p><h1 className="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">{getGreeting(now?.getHours() || 9)}, {user?.firstName || "Contractor"}</h1><p className="mt-3 text-sm text-slate-600">{date}</p></div><div className="flex flex-wrap items-center gap-2"><label className="sr-only" htmlFor="home-project">Current project</label><select id="home-project" value={projectId} onChange={() => undefined} disabled className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold"><option value="">All projects</option><option value="pending">Project selector pending API</option></select><Link href="/command-center" className="rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-600">Open command center</Link></div></section>
    <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><SectionTitle title="Today" link={["Open site view", "/site-dashboard"]} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><PendingCard title="Active sites" detail="Today's active sites and planned work." /><PendingCard title="Attendance" detail="Workers expected and present today." /><PendingCard title="Operations" detail="Machines running and materials received." /><PendingCard title="Due today" detail="Payments and approvals due today." /></div></section>
    <section className="mt-8"><SectionTitle title="Quick actions" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{actions.map(([label, href]) => <Link key={href} href={href} className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-bold shadow-sm transition hover:-translate-y-0.5 hover:border-orange-300 hover:text-orange-700">+ {label}</Link>)}</div></section>
    <section className="mt-8"><SectionTitle title="Business health" link={["Owner view", "/owner-dashboard"]} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><PendingCard title="Revenue" detail="Backend financial summary required." /><PendingCard title="Expenses" detail="Backend financial summary required." /><PendingCard title="Profit" detail="Backend financial calculations required." /><PendingCard title="Receivables" detail="Client invoice API required." /><PendingCard title="Payables" detail="Supplier and worker payment API required." /><PendingCard title="Cash position" detail="Cash-flow API required." /></div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><SectionTitle title="Project health overview" link={["View projects", "/projects"]} /><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><p className="font-semibold text-slate-800">No project records available</p><p className="mt-2 text-sm text-slate-500">Project, client, progress, budget, schedule, and site health APIs are required.</p><Link href="/projects" className="mt-5 inline-block rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Open project workspace</Link></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><SectionTitle title="Needs your attention" link={["View alerts", "/alerts"]} /><ul className="space-y-2">{attentionItems.map((item) => <li key={item} className="flex items-center justify-between rounded-lg border border-slate-100 px-3 py-3 text-sm"><span>{item}</span><span className="text-xs font-semibold text-amber-700">API required</span></li>)}</ul></div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><SectionTitle title="Live site activity" link={["Activity stream", "/activity-stream"]} /><p className="text-sm text-slate-500">Normal API refresh or WebSocket/SSE integration is required for live activity.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><SectionTitle title="Project map" link={["Location view", "/location"]} /><div className="grid min-h-32 place-items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-center text-sm text-slate-500">Map and project location API required</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><SectionTitle title="Working condition" link={["Site diary", "/site-diary"]} /><p className="text-sm text-slate-500">Weather and site-condition API required. No weather claim is displayed.</p></div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><SectionTitle title="Cash flow snapshot" link={["Open cash flow", "/cash-flow"]} /><div className="grid grid-cols-2 gap-3"><PendingCard title="Money in" detail="Today, 7 days, 30 days, 3 months." /><PendingCard title="Money out" detail="Today, 7 days, 30 days, 3 months." /></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><SectionTitle title="Tomorrow preview" link={["Open calendar", "/calendar"]} /><p className="text-sm text-slate-500">Scheduled projects, resources, deliveries, tasks, and deadlines require calendar APIs.</p></div></section>
    <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><SectionTitle title="System connection" /><div className="flex flex-wrap items-center gap-3 text-sm">{health ? <span className="rounded-full bg-emerald-50 px-3 py-1.5 font-semibold text-emerald-700">Backend connected: {health.status}</span> : healthError ? <ErrorState message={healthError} /> : <Loading />}<span className="text-slate-500">Role: {role}. Business data remains empty until domain APIs are available.</span></div></section>
  </div></main>;
}
