"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { PasswordInput } from "@/components/auth/password-input";
import { authApi } from "@/lib/api/auth-api";
import { auth } from "@/lib/auth/auth";
import type { ApiError } from "@/types/api";
const valid = (value: string) => /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/.test(value);
export default function SecurityPage() { const router = useRouter(), [currentPassword, setCurrent] = useState(""), [newPassword, setNew] = useState(""), [confirmPassword, setConfirm] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(false), [allLoading, setAllLoading] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!currentPassword) return setError("Current password is required."); if (!valid(newPassword)) return setError("New password must meet the stated password requirements."); if (newPassword !== confirmPassword) return setError("Passwords do not match."); setLoading(true); setError(""); try { await authApi.changePassword({ currentPassword, newPassword, confirmPassword }); auth.clear(); router.replace("/login"); } catch (reason) { setError((reason as ApiError).message); } finally { setLoading(false); } }; const logoutAll = async () => { setAllLoading(true); setError(""); try { await auth.logoutAll(); router.replace("/login"); } catch (reason) { setError((reason as ApiError).message); } finally { setAllLoading(false); } }; return <div className="max-w-xl"><h1 className="text-2xl font-bold">Security</h1><p className="mt-1 text-sm text-slate-500">Manage your password and active sessions.</p><section className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Change password</h2><form onSubmit={submit} className="mt-4 space-y-4"><PasswordInput label="Current password" value={currentPassword} onChange={setCurrent} disabled={loading} /><PasswordInput label="New password" value={newPassword} onChange={setNew} disabled={loading} autoComplete="new-password" /><PasswordInput label="Confirm new password" value={confirmPassword} onChange={setConfirm} disabled={loading} autoComplete="new-password" />{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{loading ? "Changing password…" : "Change password"}</button></form></section><section className="mt-6 rounded-xl border border-red-200 bg-white p-6"><h2 className="font-semibold text-slate-900">All devices</h2><p className="mt-1 text-sm text-slate-500">Sign out every active session, including this one.</p><button onClick={logoutAll} disabled={allLoading} className="mt-4 rounded-lg border border-red-300 px-4 py-2.5 text-sm font-medium text-red-700 disabled:opacity-60">{allLoading ? "Signing out…" : "Logout from all devices"}</button></section></div>; }
