"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AuthShell } from "@/components/auth/auth-shell";
import { PasswordInput } from "@/components/auth/password-input";
import { authApi } from "@/lib/api/auth-api";
import type { ApiError } from "@/types/api";
const valid = (value: string) => /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/.test(value);
export default function ResetPasswordPage() { const router = useRouter(), [context, setContext] = useState<{ email: string; otp: string } | null>(null), [password, setPassword] = useState(""), [confirmPassword, setConfirmPassword] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(false), [success, setSuccess] = useState(""); useEffect(() => { try { setContext(JSON.parse(sessionStorage.getItem("smartroad_reset_context") || "null")); } catch { setContext(null); } }, []); const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!context) return; if (!valid(password)) return setError("Password must have 8+ characters with upper/lowercase, a number, and a special character."); if (password !== confirmPassword) return setError("Passwords do not match."); setLoading(true); setError(""); try { await authApi.resetPassword({ ...context, newPassword: password, confirmPassword }); sessionStorage.removeItem("smartroad_reset_context"); setSuccess("Password reset successfully. Redirecting to sign in…"); setTimeout(() => router.replace("/login"), 900); } catch (reason) { setError((reason as ApiError).message); } finally { setLoading(false); } }; if (context === null) return <AuthShell title="Reset password" subtitle="Verify your reset code before choosing a new password." />; return <AuthShell title="Choose a new password" subtitle="Use a strong password you don’t use elsewhere."><form onSubmit={submit} className="mt-6 space-y-4"><PasswordInput label="New password" value={password} onChange={setPassword} disabled={loading} autoComplete="new-password" /><PasswordInput label="Confirm password" value={confirmPassword} onChange={setConfirmPassword} disabled={loading} autoComplete="new-password" />{error && <p role="alert" className="text-sm text-red-600">{error}</p>}{success && <p className="text-sm text-emerald-700">{success}</p>}<button disabled={loading || Boolean(success)} className="w-full rounded-lg bg-slate-900 py-2.5 text-white disabled:opacity-60">{loading ? "Resetting password…" : "Reset password"}</button></form></AuthShell>; }
