"use client";

import { useEffect, useRef, useState } from "react";

export function SignaturePad() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [saved, setSaved] = useState(false);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext("2d"); if (!context) return; context.lineWidth = 2; context.lineCap = "round"; context.strokeStyle = "#15231e"; const point = (event: PointerEvent) => { const bounds = canvas.getBoundingClientRect(); return { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; }; let drawing = false; const start = (event: PointerEvent) => { drawing = true; const position = point(event); context.beginPath(); context.moveTo(position.x, position.y); canvas.setPointerCapture(event.pointerId); }; const draw = (event: PointerEvent) => { if (!drawing) return; const position = point(event); context.lineTo(position.x, position.y); context.stroke(); }; const stop = () => { drawing = false; }; canvas.addEventListener("pointerdown", start); canvas.addEventListener("pointermove", draw); canvas.addEventListener("pointerup", stop); canvas.addEventListener("pointerleave", stop); return () => { canvas.removeEventListener("pointerdown", start); canvas.removeEventListener("pointermove", draw); canvas.removeEventListener("pointerup", stop); canvas.removeEventListener("pointerleave", stop); }; }, []);
  const clear = () => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (canvas && context) context.clearRect(0, 0, canvas.width, canvas.height); setSaved(false); };
  return <div className="max-w-xl rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-slate-800">Draw signature</p><canvas ref={canvasRef} width={640} height={220} aria-label="Signature drawing area" className="mt-3 h-44 w-full touch-none rounded-lg border border-dashed border-slate-300 bg-slate-50" /><div className="mt-3 flex gap-2"><button type="button" onClick={clear} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Clear</button><button type="button" onClick={() => setSaved(true)} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save signature</button></div>{saved && <p role="status" className="mt-3 text-sm text-emerald-700">Signature preview saved locally. Backend storage is pending.</p>}</div>;
}
